#!/usr/bin/env python3
"""
extract_to_classic.py — extract code from .ipynb into the classic/ directory (split package layout)

Each code cell's metadata["tags"] marks a module; this script splits the
notebooks into standalone modules, mirroring the main_zh branch layout:

    classic/
    ├── core/                     # from core/core.ipynb (CC-BY-4.0)
    │   ├── __init__.py
    │   ├── config.py             #  @config
    │   ├── test.py               #  @test      (V1)
    │   ├── test_func.py          #  @test_func
    │   ├── test2.py              #  @test2     (V2)
    │   ├── test3.py              #  @test3     (V3)
    │   └── test4.py              #  @test4     (V4)
    ├── func/                     # from features/func2.ipynb (MIT)
    │   ├── __init__.py
    │   ├── test2_1.py            #  @test2_1   (V2.1)
    │   ├── test2_5.py            #  @test2_5   (V2.5)
    │   ├── get_google_result.py  # copied from features/
    │   └── get_google_result2.py # copied from features/
    └── demo/                     # copied from demos/ (WTFPL)
        ├── demo.py
        ├── demo_1.py
        └── demo_5.py

classic/ is git-ignored.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "classic"

NOTEBOOKS = [
    (ROOT / "core" / "core.ipynb", "core", "CC-BY-4.0"),
    (ROOT / "features" / "func2.ipynb", "func", "MIT"),
]

# The notebooks share a single namespace (the original code only rewrites
# test./test2. module-qualified references into bare variables). After the
# split, each module needs a standard import header injected:
MODULE_HEADERS = {
    # core/ package
    "config": [],
    "test": ["import re", "", "from core.config import SEP, VOCAB_HEADS"],
    "test_func": ["import random", "", "from core.config import SEP"],
    "test2": ["from core.test import bigram_counts", "from core.config import SEP"],
    "test3": ["from core.test import bigram_counts", "from core.test2 import cooccurrence_counts", "from core.config import SEP"],
    "test4": ["from itertools import pairwise", "from core.config import SEP"],
    # func/ package
    "test2_1": ["from core.test import count_bigrams", "from core.test2 import count_cooccurrence, generate"],
    "test2_5": ["import re", "", "from core.test import bigram_counts, split_words", "from core.config import SEP", "from core.test2 import cooccurrence_counts, count_cooccurrence, weighted_score"],
}

COPY_FILES = [
    (ROOT / "features" / "get_google_result.py", "func/get_google_result.py"),
    (ROOT / "features" / "get_google_result2.py", "func/get_google_result2.py"),
    (ROOT / "demos" / "demo.py", "demo/demo.py"),
    (ROOT / "demos" / "demo_1.py", "demo/demo_1.py"),
    (ROOT / "demos" / "demo_5.py", "demo/demo_5.py"),
]

SPDX_HEADER = """# SPDX-License-Identifier: {license_id}
# Extracted automatically by extract_to_classic.py from {source}.
# Upstream docs: https://github.com/BYXY01/stone-age-NLP
"""


def grouped_cells(ipynb_path: Path) -> dict:
    """按 cell 的 metadata["tags"][0] 分组，返回 {tag: [code_block, ...]}。
    无 tag 的 code cell（如依赖导入）跳过，不生成模块。"""
    nb = json.loads(ipynb_path.read_text(encoding="utf-8"))
    groups = {}
    order = []
    for cell in nb["cells"]:
        if cell["cell_type"] != "code":
            continue
        tags = cell["metadata"].get("tags") or []
        if not tags:
            continue
        tag = tags[0]
        code = "".join(cell["source"]).rstrip() + "\n"
        if tag not in groups:
            groups[tag] = []
            order.append(tag)
        groups[tag].append(code)
    return {tag: "\n".join(groups[tag]) for tag in order}


def build_module(ipynb_path: Path, pkg: str, tag: str, license_id: str):
    """把某个标记下的全部代码写为 classic/<pkg>/<tag>.py，注入模块头。"""
    code = grouped_cells(ipynb_path)[tag]
    header_lines = MODULE_HEADERS.get(tag, [])
    body = "\n\n".join(header_lines + [code]) + "\n" if header_lines else code + "\n"
    header = SPDX_HEADER.format(license_id=license_id, source=f"{ipynb_path} (cell @{tag})")
    out = OUT / pkg / f"{tag}.py"
    out.write_text(header + body, encoding="utf-8")
    print(f"  ✓ {pkg}/{tag}.py  ({license_id})")


def copy_file(src: Path, rel: str, license_id: str):
    text = src.read_text(encoding="utf-8")
    header = SPDX_HEADER.format(license_id=license_id, source=str(src))
    out = OUT / rel
    out.write_text(header + text, encoding="utf-8")
    print(f"  ✓ {rel}  ({license_id})")


def write_init(pkg: str, submodules: list):
    init = OUT / pkg / "__init__.py"
    body = "# Generated by extract_to_classic.py\n"
    for mod in submodules:
        body += f"from .{mod} import *\n"
    init.write_text(body, encoding="utf-8")
    print(f"  ✓ {pkg}/__init__.py")


def main():
    OUT.mkdir(exist_ok=True)
    print("Extracting to classic/ ...")
    for nb, pkg, lic in NOTEBOOKS:
        (OUT / pkg).mkdir(exist_ok=True)
        tags = list(grouped_cells(nb))
        for tag in tags:
            build_module(nb, pkg, tag, lic)
        write_init(pkg, tags)
    for src, rel in COPY_FILES:
        lic = "WTFPL" if rel.startswith("demo/") else "MIT"
        out = OUT / rel
        out.parent.mkdir(exist_ok=True)
        copy_file(src, rel, lic)
    print("\nDone. Run a demo:")
    print("  python demos/demo_1.py")


if __name__ == "__main__":
    main()